# MolSSI Day 1 Project - Distance between Atoms in Water

In [89]:
import numpy

In [90]:
import os

In [111]:
pwd

'C:\\Users\\owner\\Desktop\\cms-workshop\\data\\data'

In [112]:
cd ..

C:\Users\owner\Desktop\cms-workshop\data


In [113]:
water_file = os.path.join('data','outfiles','water.out')
print(water_file)

data\outfiles\water.out


In [114]:
water_file = os.path.join('data','water.xyz')
print(water_file)

data\water.xyz


In [120]:
outfile = open(water_file,'r')
data = outfile.readlines()

In [119]:
print(data)

['3\n', 'Water xyz file\n', 'O        0.000000     -0.007156      0.965491\n', 'H1      -0.000000      0.001486     -0.003471\n', 'H2       0.000000      0.931026      1.207929\n']


In [121]:
xyz_coord = numpy.genfromtxt(fname=water_file, delimiter=' ', dtype='unicode')
print(xyz_coord)

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 20 columns instead of 1)
    Line #4 (got 18 columns instead of 1)
    Line #5 (got 20 columns instead of 1)

In [117]:
xyz_coord = numpy.genfromtxt(fname=water_file, delimiter=' ', dtype='unicode')
print(xyz_coord)

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 20 columns instead of 1)
    Line #4 (got 18 columns instead of 1)
    Line #5 (got 20 columns instead of 1)

In [156]:
#make water file
water_file = os.path.join('data','water.xyz')
#make geom file
geom_file = open(water_file,'r')
water_lines = geom_file.readlines()
print(water_lines)

['3\n', 'Water xyz file\n', 'O        0.000000     -0.007156      0.965491\n', 'H1      -0.000000      0.001486     -0.003471\n', 'H2       0.000000      0.931026      1.207929\n']


In [157]:
atom_lines = water_lines[2:]
#generate array
atoms = numpy.genfromtxt(fname=atom_lines, dtype='unicode')
print(atoms)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [158]:
#define atom names
atom_names = atoms[:,0]
print(atom_names)

['O' 'H1' 'H2']


In [159]:
#define atom coord
atom_coords = atoms[:,1:]
print(atom_coords)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [160]:
atom_coords = atom_coords.astype(numpy,float)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


In [161]:
atom_coords = atom_coords.astype(numpy.float)

In [162]:
#make atom coordinates as floating point numbers
atom_coords = atom_coords.astype(numpy.float)

In [163]:
print(atom_coords)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [164]:
for i,atom in enumerate(atom_names):
    print(atom,atom_coords[i])

O [ 0.       -0.007156  0.965491]
H1 [-0.        0.001486 -0.003471]
H2 [0.       0.931026 1.207929]


In [165]:
O_H1_diff = atom_coords[1,:]-atom_coords[0,:]

In [166]:
print(O_H1_diff)

[-0.        0.008642 -0.968962]


In [167]:
O_H1_dist = numpy.sqrt((O_H1_diff[0]**2)+(O_H1_diff[1]**2)+(O_H1_diff[2]**2))

In [168]:
print(O_H1_dist)

0.9690005374652793


In [169]:
for i,atom in enumerate(atom_names):
    atom_list_size = len(atom_names)
    next_atom_ind = i+1
    for j in range(next_atom_ind,atom_list_size):
        x_dist = atom_coords[j,0] - atom_coords[i,0]
        y_dist = atom_coords[j,1] - atom_coords[i,1]
        z_dist = atom_coords[j,2] - atom_coords[i,2]
        bond_length = numpy.sqrt(x_dist**2 + y_dist**2 + z_dist**2)
        print(atom,atom_names[j])
        print(bond_length)

O H1
0.9690005374652793
O H2
0.9690003348647513
H1 H2
1.52693633514957


In [170]:
for i,atom in enumerate(atom_names):
    atom_list_size = len(atom_names)
    next_atom_ind = i+1
    for j in range(next_atom_ind,atom_list_size):
        x_dist = atom_coords[j,0] - atom_coords[i,0]
        y_dist = atom_coords[j,1] - atom_coords[i,1]
        z_dist = atom_coords[j,2] - atom_coords[i,2]
        distance = numpy.sqrt(x_dist**2 + y_dist**2 + z_dist**2)
        bond_length = (atom_names(i),atom_names(j),distance)
        print(bond_length)

TypeError: 'numpy.ndarray' object is not callable

In [171]:
bond_length = []
for i,atom in enumerate(atom_names):
    atom_list_size = len(atom_names)
    next_atom_ind = i+1
    for j in range(next_atom_ind,atom_list_size):
        x_dist = atom_coords[j,0] - atom_coords[i,0]
        y_dist = atom_coords[j,1] - atom_coords[i,1]
        z_dist = atom_coords[j,2] - atom_coords[i,2]
        distance = numpy.sqrt(x_dist**2 + y_dist**2 + z_dist**2)
        bond_length.append([atom_names[i],atom_names[j],distance])
print(bond_length)

[['O', 'H1', 0.9690005374652793], ['O', 'H2', 0.9690003348647513], ['H1', 'H2', 1.52693633514957]]


In [172]:
dist_copy = distances
for pair in dist_copy:
    pair[2] = '%.3f' %pair[2]
    print(F'{pair[0]}-{pair[1]}: {pair[2]})

SyntaxError: EOL while scanning string literal (<ipython-input-172-93171187a147>, line 4)

In [173]:
dist_copy = bond_length
for pair in dist_copy:
    pair[2] = '%.3f' %pair[2]
    print(F'{pair[0]}-{pair[1]}: {pair[2]}')

O-H1: 0.969
O-H2: 0.969
H1-H2: 1.527


In [150]:
dist_copy = bond_length
for pair in dist_copy:
    pair[2] = '%.3f' %pair[2]
    print(F'{pair[0]}-{pair[1]}: {pair[2]}')

TypeError: must be real number, not str

In [146]:
cd data

C:\Users\owner\Desktop\cms-workshop\data\data


In [147]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 58AB-3C97

 Directory of C:\Users\owner\Desktop\cms-workshop\data\data

05/15/2019  10:38 AM    <DIR>          .
05/15/2019  10:38 AM    <DIR>          ..
05/15/2019  10:38 AM               619 benzene.xyz
05/15/2019  10:38 AM             2,471 buckminsterfullerene.xyz
05/15/2019  10:38 AM           355,359 distance_data_headers.csv
05/15/2019  10:38 AM    <DIR>          outfiles
05/15/2019  10:38 AM            61,568 sapt.out
05/15/2019  10:38 AM               155 water.xyz
               5 File(s)        420,172 bytes
               3 Dir(s)  165,111,238,656 bytes free


In [148]:
cd ..

C:\Users\owner\Desktop\cms-workshop\data


In [149]:
dist_copy = bond_length
for pair in dist_copy:
    pair[2] = '%.3f' %pair[2]
    print(F'{pair[0]}-{pair[1]}: {pair[2]}')

TypeError: must be real number, not str

In [ ]:
ls

In [ ]:
cd ..

In [ ]:
pwd